### ISSUE TITLE
Client never marks node as up again

### ISSUE THREAD

**Issue by sargun** [basho/riak-dotnet-client#283] opened 2015-07-20 18:58 UTC
I believe there is a bug in the RiakCluster / connection-pooling in the .net sdk. During a long running process, some connections become trashed (as expected). Connection pooling should dispose of these connections and create new ones. It would appear that re-creating the RiakCluster object is required to continue.

First, there is an exception on a thread: `CommunicationError: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`
Then subsequent calls on the same thread receive the following: `Exception: ClusterOffline: Unable to access functioning Riak node.`

I’ve verified manually that the whole cluster is up, and I can query it. I have also checked logs and seen nothing interesting. The network problem is clearly on our side, but the connection pool should be able to handle that.

**Comment by ness2u** [comment] 2015-07-20 21:43
The code assumes that a riak node goes down, but doesn’t account for broken network streams.

The RiakClient has a NodeMonitor method which adds/removes nodes from the load balancer queue.
It does not recreate nodes, just tests the nodes health by ping. Upon successful response; bad nodes are re-added.

RiakNode uses an IRiakConnectionManager to handle connections. Either OnTheFly or Pooled.
Based on logic, we’re using RiakConnectionPool. 
If one of these connections fails (or is unable to ping the node), it will it will get added to the RiakCluster DeadNodes queue. 
In my case, the network connection gets severed triggering this behaviour, causing the node to be put on the naughty list.

The RiakConnectionPool creates connections in the constructor, and recreates them nowhere… 
The logic around failure throws an exception, but the underlying network stream is never recreated.
NodeMonitor pings the node frequently, but since the underlying stream is no longer connected, will never resolve.
This propagates through the nodes until all nodes are offline.

**Comment by lukebakken** [comment] 2015-07-22 20:51
@sargun @ness2u - I just merged PR #284 which I believe addresses this issue.

@ness2u - Is it possible to clone this repository with that change and give it a try?

**Comment by ness2u** [comment] 2015-07-23 00:16
I didn't pull your change, but it looks like you just set the stream to null. Was there more to your change, or is that the case? If so, that alone won't fix the issue. 

You'll need to replace the bad connection in RiakConnectionPool with a new connection, pulled from the connection factory.

**Comment by lukebakken** [comment] 2015-07-23 15:14
@ness2u -

The next time the `RiakPbcSocket` is used after `networkStream` is set to `null`, this code will create a new `Socket` and `NetworkStream` transparently:

```csharp

        private Stream NetworkStream
        {
            get
            {
                if (networkStream == null)
                {
                    SetUpNetworkStream();
                }

                return networkStream;
            }
        }
```

All access to `networkStream` is via this property. There is no need to re-create the socket used in a `RiakConnection`.

Since you can reproduce this issue easily, it would be great if you could give this change a try. Please let me know if that is possible.

**Comment by ness2u** [comment] 2015-07-27 17:49
Sorry @lukebakken, I did not notice that.
I merged your changes and am running the test now. It is worth noting that our network issues are consistently inconsistent... I'll update back if I see the issue again, otherwise, assume that it worked.

**Comment by alexmoore** [comment] 2015-07-27 18:07
Thanks @ness2u! Please let us know the results either way.

**Comment by ness2u** [comment] 2015-07-28 20:01
I ran my tool overnight, about 1.2M gets/puts with no unrecovered connection pools.
Thank you.

**Comment by alexmoore** [comment] 2015-07-30 19:45
Hi @sargun & @ness2u, 

I've promoted the fix to NuGet: https://www.nuget.org/packages/RiakClient/2.1.1

Thanks!
Alex

**Closed by alexmoore** 2015-07-30 19:46 UTC
